--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Blackrock Spire.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Blackrock Spire", {
	{ id = 4788, name = "The Final Tablets", level = 58, minLevel = 40, startedBy = "Prospector Ironboot", startZone = "Tanaris", startZoneMap = 1446, startedById = 10460, startedByDisplay = 10195 },
	{ id = 4982, name = "Bijou's Belongings", level = 59, minLevel = 55, side = "Horde", startedBy = "Bijou", startZone = "Blackrock Spire", startZoneMap = 253, startedById = 10257, startedByDisplay = 9553 },
	{ id = 5001, name = "Bijou's Belongings", level = 59, minLevel = 55, side = "Alliance", startedBy = "Bijou", startZone = "Blackrock Spire", startZoneMap = 253, startedById = 10257, startedByDisplay = 9553 },
	{ id = 4983, name = "Bijou's Reconnaissance Report", level = 59, minLevel = 55, side = "Horde", startedBy = "Bijou", startZone = "Blackrock Spire", startZoneMap = 253, startedById = 10257, startedByDisplay = 9553, rewards = { 15858, 15859 } },
	{ id = 4862, name = "En-Ay-Es-Tee-Why", level = 59, minLevel = 55, startedBy = "Kibler", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 10260, startedByDisplay = 9561, rewards = { 12529 } },
	{ id = 4729, name = "Kibler's Exotic Pets", level = 59, minLevel = 55, startedBy = "Kibler", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 10260, startedByDisplay = 9561, rewards = { 12264 } },
	{ id = 5002, name = "Message to Maxwell", level = 59, minLevel = 55, side = "Alliance", startedBy = "Bijou", startZone = "Blackrock Spire", startZoneMap = 253, startedById = 10257, startedByDisplay = 9553 },
	{ id = 4981, name = "Operative Bijou", level = 59, minLevel = 55, side = "Horde", startedBy = "Lexlort", startZone = "Badlands", startZoneMap = 1418, startedById = 9080, startedByDisplay = 8333 },
	{ id = 4701, name = "Put Her Down", level = 59, minLevel = 55, side = "Alliance", startedBy = "Helendis Riverhorn", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 9562, startedByDisplay = 8694, rewards = { 15824, 15825, 15827 } },
	{ id = 4724, name = "The Pack Mistress", level = 59, minLevel = 55, side = "Horde", startedBy = "Galamav the Marksman", startZone = "Badlands", startZoneMap = 1418, startedById = 9081, startedByDisplay = 8334, rewards = { 15824, 15825, 15827 } },
	{ id = 7761, name = "Blackhand's Command", level = 60, minLevel = 55 },
	{ id = 6602, name = "Blood of the Black Dragon Champion", level = 60, minLevel = 55, side = "Horde", startedBy = "Rexxar", startZone = "Feralas", startZoneMap = 1444, startedById = 10182, startedByDisplay = 11660, rewards = { 16309 } },
	{ id = 4765, name = "Delivery to Ridgewell", level = 60, minLevel = 57, side = "Alliance", startedBy = "Mayara Brightwing", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 9565, startedByDisplay = 8695, rewards = { 15860, 15861 } },
	{ id = 4764, name = "Doomrigger's Clasp", level = 60, minLevel = 57, side = "Alliance", startedBy = "Mayara Brightwing", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 9565, startedByDisplay = 8695 },
	{ id = 6502, name = "Drakefire Amulet", level = 60, minLevel = 50, side = "Alliance", startedBy = "Haleh", startZone = "Winterspring", startZoneMap = 1452, startedById = 10929, startedByDisplay = 10199, rewards = { 16309 } },
	{ id = 4735, name = "Egg Collection", level = 60, minLevel = 57, startedBy = "Tinkee Steamboil", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 10267, startedByDisplay = 9791 },
	{ id = 4734, name = "Egg Freezing", level = 60, minLevel = 57, startedBy = "Tinkee Steamboil", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 10267, startedByDisplay = 9791, rewards = { 12144 } },
	{ id = 4974, name = "For The Horde!", level = 60, minLevel = 55, side = "Horde", startedBy = "Thrall", startZone = "Orgrimmar", startZoneMap = 1454, startedById = 4949, startedByDisplay = 4527, rewards = { 13965, 13966, 13968 } },
	{ id = 5089, name = "General Drakkisath's Command", level = 60, minLevel = 55, side = "Alliance", startedBy = "Sergeant Major Skyshadow", startZone = "Champions Hall", startedById = 12780, startedByDisplay = 12924 },
	{ id = 5102, name = "General Drakkisath's Demise", level = 60, minLevel = 55, side = "Alliance", startedBy = "Marshal Maxwell", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 9560, startedByDisplay = 8685, rewards = { 13965, 13966, 13968 } },
	{ id = 5081, name = "Maxwell's Mission", level = 60, minLevel = 55, side = "Alliance", startedBy = "Marshal Maxwell", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 9560, startedByDisplay = 8685, rewards = { 13958, 13959, 13961, 13962, 13963 } },
	{ id = 4766, name = "Mayara Brightwing", level = 60, minLevel = 57, side = "Alliance", startedBy = "Count Remington Ridgewell", startZone = "Stormwind City", startZoneMap = 1453, startedById = 2285, startedByDisplay = 5075 },
	{ id = 4866, name = "Mother's Milk", level = 60, minLevel = 55, startedBy = "Ragged John", startZone = "Burning Steppes", startZoneMap = 1428, startedById = 9563, startedByDisplay = 8696, rewards = { 15873 } },
	{ id = 6569, name = "Oculus Illusions", level = 60, minLevel = 55, side = "Horde", startedBy = "Myranda the Hag", startZone = "Western Plaguelands", startZoneMap = 1422, startedById = 11872, startedByDisplay = 11800 },
	{ id = 4742, name = "Seal of Ascension", level = 60, minLevel = 57, startedBy = "Vaelan", startedById = 10296, startedByDisplay = 9643 },
	{ id = 4743, name = "Seal of Ascension", level = 60, minLevel = 57, startedBy = "Vaelan", startedById = 10296, startedByDisplay = 9643, rewards = { 12344 } },
	{ id = 4768, name = "The Darkstone Tablet", level = 60, minLevel = 57, side = "Horde", startedBy = "Shadowmage Vivian Lagrave", startZone = "Badlands", startZoneMap = 1418, startedById = 9078, startedByDisplay = 8330, rewards = { 15860, 15861 } },
	{ id = 5127, name = "The Demon Forge", level = 60, minLevel = 55, startedBy = "Lorax", startZone = "Winterspring", startZoneMap = 1452, startedById = 10918, startedByDisplay = 11513, rewards = { 9224, 12696, 12849 } },
	{ id = 8966, name = "The Left Piece of Lord Valthalak's Amulet", level = 60, minLevel = 58, startedBy = "Bodley", startedById = 16033, startedByDisplay = 15994 },
	{ id = 5160, name = "The Matron Protectorate", level = 60, minLevel = 57, startedBy = "Awbee", startZone = "Blackrock Spire", startZoneMap = 253, startedById = 10740, startedByDisplay = 6293 },
	{ id = 8989, name = "The Right Piece of Lord Valthalak's Amulet", level = 60, minLevel = 58, startedBy = "Bodley", startedById = 16033, startedByDisplay = 15994 },
	{ id = 4907, name = "Tinkee Steamboil", level = 60, minLevel = 57, startedBy = "Felnok Steelspring", startZone = "Winterspring", startZoneMap = 1452, startedById = 10468, startedByDisplay = 10655 },
	{ id = 4867, name = "Urok Doomhowl", level = 60, minLevel = 55, startedBy = "Warosh", startZone = "Blackrock Spire", startZoneMap = 253, startedById = 10799, startedByDisplay = 763, rewards = { 15867 } },
	{ id = 4769, name = "Vivian Lagrave and the Darkstone Tablet", level = 60, minLevel = 57, side = "Horde", startedBy = "Apothecary Zinge", startZone = "Undercity", startZoneMap = 1458, startedById = 5204, startedByDisplay = 4056 },
	{ id = 4903, name = "Warlord's Command", level = 60, minLevel = 55, side = "Horde", startedBy = "Warlord Goretooth", startZone = "Badlands", startZoneMap = 1418, startedById = 9077, startedByDisplay = 8331, rewards = { 13958, 13959, 13961, 13962, 13963 } },
})
