--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Blackrock Depths.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Blackrock Depths", {
	{ id = 4295, name = "Rocknot's Ale", level = 1, minLevel = 1, startedBy = "Private Rocknot", startZone = "Blackrock Depths Shadowforge City", startedById = 9503, startedByDisplay = 8654 },
	{ id = 3981, name = "Commander Gor'shak", level = 52, minLevel = 48, side = "Horde", startedBy = "Galamav the Marksman", startZone = "Badlands", startedById = 9081, startedByDisplay = 8334 },
	{ id = 3801, name = "Dark Iron Legacy", level = 52, minLevel = 48, startedBy = "Franclorn Forgewright", startedById = 8888, startedByDisplay = 8698 },
	{ id = 3802, name = "Dark Iron Legacy", level = 52, minLevel = 48, startedBy = "Franclorn Forgewright", startedById = 8888, startedByDisplay = 8698, rewards = { 11000 } },
	{ id = 4081, name = "KILL ON SIGHT: Dark Iron Dwarves", level = 52, minLevel = 48, side = "Horde" },
	{ id = 4136, name = "Ribbly Screwspigot", level = 53, minLevel = 48, startedBy = "Yuka Screwspigot", startZone = "Burning Steppes", startedById = 9544, startedByDisplay = 8665, rewards = { 11865, 11963, 12049 } },
	{ id = 4324, name = "Yuka Screwspigot", level = 53, minLevel = 48, startedBy = "Yorba Screwspigot", startZone = "Tanaris", startedById = 9706, startedByDisplay = 11388 },
	{ id = 4242, name = "Abandoned Hope", level = 54, minLevel = 48, side = "Alliance", startedBy = "Marshal Windsor", startZone = "Blackrock Depths Shadowforge City", startedById = 9023, startedByDisplay = 8707, rewards = { 12018, 12021, 12041 } },
	{ id = 4082, name = "KILL ON SIGHT: High Ranking Dark Iron Officials", level = 54, minLevel = 50, side = "Horde" },
	{ id = 4241, name = "Marshal Windsor", level = 54, minLevel = 48, side = "Alliance", startedBy = "Marshal Maxwell", startZone = "Burning Steppes", startedById = 9560, startedByDisplay = 8685 },
	{ id = 4002, name = "The Eastern Kingdom", level = 54, minLevel = 48, side = "Horde", startedBy = "Thrall", startZone = "Orgrimmar", startedById = 4949, startedByDisplay = 4527 },
	{ id = 7201, name = "The Last Element", level = 54, minLevel = 48, side = "Horde", startedBy = "Shadowmage Vivian Lagrave", startZone = "Badlands", startedById = 9078, startedByDisplay = 8330, rewards = { 12038 } },
	{ id = 4201, name = "The Love Potion", level = 54, minLevel = 50, startedBy = "Mistress Nagmara", startZone = "Blackrock Depths Shadowforge City", startedById = 9500, startedByDisplay = 2834, rewards = { 11866, 11962 } },
	{ id = 3982, name = "What Is Going On?", level = 54, minLevel = 48, side = "Horde", startedBy = "Commander Gor\\'shak", startZone = "Blackrock Depths Shadowforge City", startedById = 9020, startedByDisplay = 8703 },
	{ id = 4001, name = "What Is Going On?", level = 54, minLevel = 48, side = "Horde", startedBy = "Commander Gor\\'shak", startZone = "Blackrock Depths Shadowforge City", startedById = 9020, startedByDisplay = 8703 },
	{ id = 4126, name = "Hurley Blackbreath", level = 55, minLevel = 50, side = "Alliance", startedBy = "Ragnar Thunderbrew", startZone = "Dun Morogh", startedById = 1267, startedByDisplay = 1684, rewards = { 11964, 12000, 12003 } },
	{ id = 4134, name = "Lost Thunderbrew Recipe", level = 55, minLevel = 50, side = "Horde", startedBy = "Shadowmage Vivian Lagrave", startZone = "Badlands", startedById = 9078, startedByDisplay = 8330, rewards = { 3928, 6149, 11964, 12000 } },
	{ id = 4128, name = "Ragnar Thunderbrew", level = 55, minLevel = 50, side = "Alliance", startedBy = "Enohar Thunderbrew", startZone = "Blasted Lands", startedById = 9540, startedByDisplay = 8659 },
	{ id = 4123, name = "The Heart of the Mountain", level = 55, minLevel = 50, startedBy = "Maxwort Uberglint", startZone = "Burning Steppes", startedById = 9536, startedByDisplay = 8656 },
	{ id = 4083, name = "The Spectral Chalice", level = 55, minLevel = 40 },
	{ id = 4133, name = "Vivian Lagrave", level = 55, minLevel = 50, side = "Horde", startedBy = "Apothecary Zinge", startZone = "Undercity", startedById = 5204, startedByDisplay = 4056 },
	{ id = 3907, name = "Disharmony of Fire", level = 56, minLevel = 48, side = "Horde", startedBy = "Thunderheart", startZone = "Badlands", startedById = 9084, startedByDisplay = 8350, rewards = { 12112, 12113, 12114, 12115 } },
	{ id = 4263, name = "Incendius!", level = 56, minLevel = 48, side = "Alliance", startedBy = "Jalinda Sprig", startZone = "Burning Steppes", startedById = 9561, startedByDisplay = 8693, rewards = { 12112, 12113, 12114, 12115 } },
	{ id = 4286, name = "The Good Stuff", level = 56, minLevel = 50, side = "Alliance", startedBy = "Oralius", startZone = "Burning Steppes", startedById = 9177, startedByDisplay = 8872, rewards = { 11883 } },
	{ id = 4264, name = "A Crumpled Up Note", level = 58, minLevel = 50, side = "Alliance", startedBy = "Gordok Spirit", startZone = "Dire Maul", startedById = 11446, startedByDisplay = 13093 },
	{ id = 4282, name = "A Shred of Hope", level = 58, minLevel = 50, side = "Alliance", startedBy = "Marshal Windsor", startZone = "Blackrock Depths Shadowforge City", startedById = 9023, startedByDisplay = 8707 },
	{ id = 4024, name = "A Taste of Flame", level = 58, minLevel = 52, startedBy = "Cyrus Therepentous", startZone = "Burning Steppes", startedById = 9459, startedByDisplay = 2552, rewards = { 12066, 12082, 12083 } },
	{ id = 4122, name = "Grark Lorkrub", level = 58, minLevel = 52, side = "Horde", startedBy = "Lexlort", startZone = "Badlands", startedById = 9080, startedByDisplay = 8333 },
	{ id = 4322, name = "Jail Break!", level = 58, minLevel = 50, side = "Alliance", startedBy = "Marshal Windsor", startZone = "Blackrock Depths Shadowforge City", startedById = 9023, startedByDisplay = 8707, rewards = { 12061, 12062, 12065 } },
	{ id = 4132, name = "Operation: Death to Angerforge", level = 58, minLevel = 52, side = "Horde", startedBy = "Warlord Goretooth", startZone = "Badlands", startedById = 9077, startedByDisplay = 8331, rewards = { 12059 } },
	{ id = 4121, name = "Precarious Predicament", level = 58, minLevel = 52, side = "Horde", startedBy = "Grark Lorkrub", startZone = "Burning Steppes", startedById = 9520, startedByDisplay = 8697 },
	{ id = 4063, name = "The Rise of the Machines", level = 58, minLevel = 52, side = "Horde", startedBy = "Lotwil Veriatus", startZone = "Badlands", startedById = 2921, startedByDisplay = 4896, rewards = { 12108, 12109, 12110, 12111 } },
	{ id = 4341, name = "Kharan Mighthammer", level = 59, minLevel = 50, side = "Alliance", startedBy = "King Magni Bronzebeard", startZone = "Ironforge", startedById = 2784, startedByDisplay = 3597 },
	{ id = 4342, name = "Kharan's Tale", level = 59, minLevel = 50, side = "Alliance", startedBy = "Kharan Mighthammer", startZone = "Blackrock Depths Shadowforge City", startedById = 9021, startedByDisplay = 8708 },
	{ id = 4361, name = "The Bearer of Bad News", level = 59, minLevel = 50, side = "Alliance", startedBy = "Kharan Mighthammer", startZone = "Blackrock Depths Shadowforge City", startedById = 9021, startedByDisplay = 8708 },
	{ id = 4362, name = "The Fate of the Kingdom", level = 59, minLevel = 50, side = "Alliance", startedBy = "King Magni Bronzebeard", startZone = "Ironforge", startedById = 2784, startedByDisplay = 3597 },
	{ id = 4363, name = "The Princess's Surprise", level = 59, minLevel = 50, side = "Alliance", startedBy = "Princess Moira Bronzebeard", startZone = "Blackrock Depths Shadowforge City", startedById = 8929, startedByDisplay = 8705, rewards = { 12543, 12548 } },
	{ id = 4003, name = "The Royal Rescue", level = 59, minLevel = 48, side = "Horde", startedBy = "Thrall", startZone = "Orgrimmar", startedById = 4949, startedByDisplay = 4527 },
	{ id = 7604, name = "A Binding Contract", level = 60, minLevel = 60, rewards = { 18592 } },
	{ id = 9015, name = "The Challenge", level = 60, minLevel = 58, startedBy = "Falrin Treeshaper", startZone = "Dire Maul", startedById = 16032, startedByDisplay = 15996 },
	{ id = 4004, name = "The Princess Saved?", level = 60, minLevel = 48, side = "Horde", startedBy = "Princess Moira Bronzebeard", startZone = "Blackrock Depths Shadowforge City", startedById = 8929, startedByDisplay = 8705, rewards = { 12544, 12545 } },
})
