--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Dire Maul.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Dire Maul", {
	{ id = 7492, name = "Camp Mojache", level = 57, minLevel = 54, side = "Horde", startedBy = "Warcaller Gorlach", startZone = "Orgrimmar", startedById = 10880, startedByDisplay = 10186 },
	{ id = 7494, name = "Feathermoon Stronghold", level = 57, minLevel = 54, side = "Alliance", startedBy = "Crier Goodman", startZone = "Stormwind City", startedById = 2198, startedByDisplay = 1525 },
	{ id = 7488, name = "Lethtendris's Web", level = 57, minLevel = 54, side = "Alliance", startedBy = "Latronicus Moonspear", startZone = "Feralas", startedById = 7877, startedByDisplay = 6988, rewards = { 18491 } },
	{ id = 7489, name = "Lethtendris's Web", level = 57, minLevel = 54, side = "Horde", startedBy = "Talo Thornhoof", startZone = "Feralas", startedById = 7776, startedByDisplay = 6996, rewards = { 18491 } },
	{ id = 7441, name = "Pusillin and the Elder Azj'Tordin", level = 58, minLevel = 54, startedBy = "Azj'Tordin", startZone = "Feralas", startedById = 14355, startedByDisplay = 14386, rewards = { 18410, 18411 } },
	{ id = 1193, name = "A Broken Trap", level = 60, minLevel = 56 },
	{ id = 8948, name = "Anthion's Old Friend", level = 60, minLevel = 58, startedBy = "Anthion Harmon", startZone = "Eastern Plaguelands", startedById = 16016, startedByDisplay = 15968 },
	{ id = 7463, name = "Arcane Refreshment", level = 60, minLevel = 60, startedBy = "Lorekeeper Lydros", startZone = "Dire Maul", startedById = 14368, startedByDisplay = 14407 },
	{ id = 7499, name = "Codex of Defense", level = 60, minLevel = 54, rewards = { 18466 } },
	{ id = 7481, name = "Elven Legends", level = 60, minLevel = 54, side = "Horde", startedBy = "Sage Korolusk", startZone = "Feralas", startedById = 14373, startedByDisplay = 14427 },
	{ id = 7482, name = "Elven Legends", level = 60, minLevel = 54, side = "Alliance", startedBy = "Scholar Runethorn", startZone = "Feralas", startedById = 14374, startedByDisplay = 14426 },
	{ id = 8949, name = "Falrin's Vendetta", level = 60, minLevel = 58, startedBy = "Falrin Treeshaper", startZone = "Dire Maul", startedById = 16032, startedByDisplay = 15996, rewards = { 22149, 22150 } },
	{ id = 7507, name = "Foror's Compendium", level = 60, minLevel = 60 },
	{ id = 5525, name = "Free Knot!", level = 60, minLevel = 57, startedBy = "Knot Thimblejack", startZone = "Dire Maul", startedById = 14338, startedByDisplay = 14381 },
	{ id = 7429, name = "Free Knot!", level = 60, minLevel = 57, startedBy = "Knot Thimblejack", startZone = "Dire Maul", startedById = 14338, startedByDisplay = 14381 },
	{ id = 7505, name = "Frost Shock and You", level = 60, minLevel = 54, rewards = { 18471 } },
	{ id = 7498, name = "Garona: A Study on Stealth and Treachery", level = 60, minLevel = 54, rewards = { 18465 } },
	{ id = 7502, name = "Harnessing Shadows", level = 60, minLevel = 54, rewards = { 18467 } },
	{ id = 7504, name = "Holy Bologna: What the Light Won't Tell You", level = 60, minLevel = 54, rewards = { 18469 } },
	{ id = 7484, name = "Libram of Focus", level = 60, minLevel = 58, startedBy = "Lorekeeper Lydros", startZone = "Dire Maul", startedById = 14368, startedByDisplay = 14407, rewards = { 18330 } },
	{ id = 7485, name = "Libram of Protection", level = 60, minLevel = 58, startedBy = "Lorekeeper Lydros", startZone = "Dire Maul", startedById = 14368, startedByDisplay = 14407, rewards = { 18331 } },
	{ id = 7483, name = "Libram of Rapidity", level = 60, minLevel = 58, startedBy = "Lorekeeper Lydros", startZone = "Dire Maul", startedById = 14368, startedByDisplay = 14407, rewards = { 18329 } },
	{ id = 7500, name = "The Arcanist's Cookbook", level = 60, minLevel = 54, rewards = { 18468 } },
	{ id = 7506, name = "The Emerald Dream...", level = 60, minLevel = 54, rewards = { 18470 } },
	{ id = 7508, name = "The Forging of Quel'Serrar", level = 60, minLevel = 60 },
	{ id = 5518, name = "The Gordok Ogre Suit", level = 60, minLevel = 56, startedBy = "Knot Thimblejack", startZone = "Dire Maul", startedById = 14338, startedByDisplay = 14381, rewards = { 18258 } },
	{ id = 5519, name = "The Gordok Ogre Suit", level = 60, minLevel = 56, startedBy = "Knot Thimblejack", startZone = "Dire Maul", startedById = 14338, startedByDisplay = 14381, rewards = { 18258 } },
	{ id = 5528, name = "The Gordok Taste Test", level = 60, minLevel = 57, startedBy = "Stomper Kreeg", startZone = "Dire Maul", startedById = 14322, startedByDisplay = 11545, rewards = { 18269, 18284 } },
	{ id = 7503, name = "The Greatest Race of Hunters", level = 60, minLevel = 54, rewards = { 18473 } },
	{ id = 8950, name = "The Instigator's Enchantment", level = 60, minLevel = 58, startedBy = "Falrin Treeshaper", startZone = "Dire Maul", startedById = 16032, startedByDisplay = 15996 },
	{ id = 8967, name = "The Left Piece of Lord Valthalak's Amulet", level = 60, minLevel = 58, startedBy = "Bodley", startedById = 16033, startedByDisplay = 15994 },
	{ id = 7501, name = "The Light and How To Swing It", level = 60, minLevel = 54, rewards = { 18472 } },
	{ id = 7461, name = "The Madness Within", level = 60, minLevel = 56, startedBy = "Shen'dralar Ancient", startZone = "Dire Maul", startedById = 14358, startedByDisplay = 14393 },
	{ id = 8990, name = "The Right Piece of Lord Valthalak's Amulet", level = 60, minLevel = 58, startedBy = "Bodley", startedById = 16033, startedByDisplay = 15994 },
	{ id = 7462, name = "The Treasure of the Shen'dralar", level = 60, minLevel = 56, side = "Alliance", startedBy = "Shen'dralar Ancient", startZone = "Dire Maul", startedById = 14358, startedByDisplay = 14393, rewards = { 18420, 18421, 18424 } },
	{ id = 7877, name = "The Treasure of the Shen'dralar", level = 60, minLevel = 56, side = "Horde", startedBy = "Shen'dralar Ancient", startZone = "Dire Maul", startedById = 14358, startedByDisplay = 14393, rewards = { 18420, 18421, 18424 } },
	{ id = 1318, name = "Unfinished Gordok Business", level = 60, minLevel = 56, rewards = { 18366, 18367, 18368, 18369 } },
	{ id = 7703, name = "Unfinished Gordok Business", level = 60, minLevel = 56, startedBy = "Captain Kromcrush", startZone = "Dire Maul", startedById = 14325, startedByDisplay = 11564, rewards = { 18366, 18367, 18368, 18369 } },
})
