--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Gnomeregan.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Gnomeregan", {
	{ id = 2922, name = "Save Techbot's Brain!", level = 26, minLevel = 20, side = "Alliance", startedBy = "Tinkmaster Overspark", startZone = "Ironforge", startedById = 7944, startedByDisplay = 7028 },
	{ id = 2923, name = "Tinkmaster Overspark", level = 26, minLevel = 20, side = "Alliance", startedBy = "Brother Sarno", startZone = "Stormwind City", startedById = 7917, startedByDisplay = 7008 },
	{ id = 2926, name = "Gnogaine", level = 27, minLevel = 20, side = "Alliance", startedBy = "Ozzie Togglevolt", startZone = "Dun Morogh", startedById = 1268, startedByDisplay = 3441 },
	{ id = 2927, name = "The Day After", level = 27, minLevel = 20, side = "Alliance", startedBy = "Gnoarn", startZone = "Ironforge", startedById = 6569, startedByDisplay = 5377 },
	{ id = 2931, name = "Castpipe's Task", level = 28, minLevel = 25, side = "Alliance", startedBy = "Gaxim Rustfizzle", startZone = "Stonetalon Mountains", startedById = 4077, startedByDisplay = 2180 },
	{ id = 2904, name = "A Fine Mess", level = 30, minLevel = 24, startedBy = "Kernobee", startZone = "Gnomeregan", startedById = 7850, startedByDisplay = 7132, rewards = { 9535, 9536 } },
	{ id = 2930, name = "Data Rescue", level = 30, minLevel = 25, side = "Alliance", startedBy = "Master Mechanic Castpipe", startZone = "Ironforge", startedById = 7950, startedByDisplay = 7041, rewards = { 9604, 9605 } },
	{ id = 2924, name = "Essential Artificials", level = 30, minLevel = 24, side = "Alliance", startedBy = "Klockmort Spannerspan", startZone = "Ironforge", startedById = 6169, startedByDisplay = 4999 },
	{ id = 2928, name = "Gyrodrillmatic Excavationators", level = 30, minLevel = 20, side = "Alliance", startedBy = "Shoni the Shilent", startZone = "Stormwind City", startedById = 6579, startedByDisplay = 5378, rewards = { 9608, 9609 } },
	{ id = 2925, name = "Klockmort's Essentials", level = 30, minLevel = 24, side = "Alliance", startedBy = "Mathiel", startZone = "Darnassus", startedById = 6142, startedByDisplay = 5083 },
	{ id = 2953, name = "More Sparklematic Action", level = 30, minLevel = 25, rewards = { 9363 } },
	{ id = 4603, name = "More Sparklematic Action", level = 30, minLevel = 25, rewards = { 9363 } },
	{ id = 4604, name = "More Sparklematic Action", level = 30, minLevel = 25, rewards = { 9363 } },
	{ id = 2962, name = "The Only Cure is More Green Glow", level = 30, minLevel = 20, side = "Alliance", startedBy = "Ozzie Togglevolt", startZone = "Dun Morogh", startedById = 1268, startedByDisplay = 3441 },
	{ id = 2951, name = "The Sparklematic 5200!", level = 30, minLevel = 25 },
	{ id = 2952, name = "The Sparklematic 5200!", level = 30, minLevel = 25, rewards = { 9363 } },
	{ id = 4601, name = "The Sparklematic 5200!", level = 30, minLevel = 25 },
	{ id = 4602, name = "The Sparklematic 5200!", level = 30, minLevel = 25 },
	{ id = 4605, name = "The Sparklematic 5200!", level = 30, minLevel = 25, rewards = { 9363 } },
	{ id = 4606, name = "The Sparklematic 5200!", level = 30, minLevel = 25, rewards = { 9363 } },
	{ id = 2945, name = "Grime-Encrusted Ring", level = 34, minLevel = 28 },
	{ id = 2947, name = "Return of the Ring", level = 34, minLevel = 28, side = "Alliance" },
	{ id = 2949, name = "Return of the Ring", level = 34, minLevel = 28, side = "Horde" },
	{ id = 2842, name = "Chief Engineer Scooty", level = 35, minLevel = 25, side = "Horde", startedBy = "Sovik", startZone = "Orgrimmar", startedById = 3413, startedByDisplay = 7136 },
	{ id = 2843, name = "Gnomer-gooooone!", level = 35, minLevel = 20, side = "Horde", startedBy = "Scooty", startZone = "Stranglethorn Vale", startedById = 7853, startedByDisplay = 7036, rewards = { 9173 } },
	{ id = 2841, name = "Rig Wars", level = 35, minLevel = 25, side = "Horde", startedBy = "Nogg", startZone = "Orgrimmar", startedById = 3412, startedByDisplay = 7135, rewards = { 9623, 9624, 9625 } },
	{ id = 2929, name = "The Grand Betrayal", level = 35, minLevel = 25, side = "Alliance", startedBy = "High Tinker Mekkatorque", startZone = "Ironforge", startedById = 7937, startedByDisplay = 7006, rewards = { 9623, 9624, 9625 } },
})
