--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Maraudon.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Maraudon", {
	{ id = 7068, name = "Shadowshard Fragments", level = 42, minLevel = 38, side = "Horde", startedBy = "Uthel\\'nay", startZone = "Orgrimmar", rewards = { 17772, 17773 } },
	{ id = 7070, name = "Shadowshard Fragments", level = 42, minLevel = 38, side = "Alliance", startedBy = "Archmage Tervosh", startZone = "Dustwallow Marsh", rewards = { 17772, 17773 } },
	{ id = 7028, name = "Twisted Evils", level = 47, minLevel = 41, startedBy = "Willow", startZone = "Desolace", rewards = { 17775, 17776, 17777, 17779 } },
	{ id = 7029, name = "Vyletongue Corruption", level = 47, minLevel = 41, side = "Horde", startedBy = "Vark Battlescar", startZone = "Desolace", rewards = { 17768, 17770, 17778 } },
	{ id = 7041, name = "Vyletongue Corruption", level = 47, minLevel = 41, side = "Alliance", startedBy = "Talendria", startZone = "Desolace", rewards = { 17768, 17770, 17778 } },
	{ id = 7067, name = "The Pariah's Instructions", level = 48, minLevel = 39, startedBy = "Centaur Pariah", startZone = "Desolace", rewards = { 17774 } },
	{ id = 7044, name = "Legends of Maraudon", level = 49, minLevel = 41, startedBy = "Cavindra", startZone = "Desolace" },
	{ id = 7046, name = "The Scepter of Celebras", level = 49, minLevel = 41, startedBy = "Celebras the Redeemed", rewards = { 17191 } },
	{ id = 7064, name = "Corruption of Earth and Seed", level = 51, minLevel = 45, side = "Horde", startedBy = "Selendra", startZone = "Desolace", rewards = { 17705, 17743, 17753 } },
	{ id = 7065, name = "Corruption of Earth and Seed", level = 51, minLevel = 45, side = "Alliance", startedBy = "Keeper Marandis", startZone = "Desolace", rewards = { 17705, 17743, 17753 } },
	{ id = 7066, name = "Seed of Life", level = 51, minLevel = 45, startedBy = "Zaetar\\'s Spirit" },
})
