--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Scarlet Monastery.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Scarlet Monastery", {
	{ id = 1113, name = "Hearts of Zeal", level = 33, minLevel = 30, side = "Horde", startedBy = "Master Apothecary Faranell", startZone = "Undercity" },
	{ id = 1051, name = "Vorrel's Revenge", level = 33, minLevel = 25, side = "Horde", startedBy = "Vorrel Sengutz", startZone = "Scarlet Monastery", rewards = { 4643, 7750, 7751 } },
	{ id = 1160, name = "Test of Lore", level = 36, minLevel = 25, side = "Horde", startedBy = "Parqual Fintallas", startZone = "Undercity" },
	{ id = 1049, name = "Compendium of the Fallen", level = 38, minLevel = 28, side = "Horde", startedBy = "Sage Truthseeker", startZone = "Thunder Bluff", rewards = { 7747, 7749, 17508 } },
	{ id = 1050, name = "Mythology of the Titans", level = 38, minLevel = 28, side = "Alliance", startedBy = "Librarian Mae Paledust", startZone = "Ironforge", rewards = { 7746 } },
	{ id = 1053, name = "In the Name of the Light", level = 40, minLevel = 34, side = "Alliance", startedBy = "Raleigh the Devout", startZone = "Hillsbrad Foothills", rewards = { 6829, 6830, 6831, 11262 } },
	{ id = 1048, name = "Into The Scarlet Monastery", level = 42, minLevel = 33, side = "Horde", startedBy = "Varimathras", startZone = "Undercity", rewards = { 6802, 6803, 10711 } },
})
