--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Scholomance.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Scholomance", {
	{ id = 5582, name = "Healthy Dragon Scale", level = 58, minLevel = 55 },
	{ id = 5529, name = "Plagued Hatchlings", level = 58, minLevel = 55, startedBy = "Betina Bigglezink", startZone = "Eastern Plaguelands", startZoneMap = 1423, startedById = 11035, startedByDisplay = 10465 },
	{ id = 5341, name = "Barov Family Fortune", level = 60, minLevel = 52, side = "Horde", startedBy = "Alexi Barov", startZone = "Tirisfal Glades", startZoneMap = 1420, startedById = 11022, startedByDisplay = 10456 },
	{ id = 5343, name = "Barov Family Fortune", level = 60, minLevel = 52, side = "Alliance", startedBy = "Weldon Barov", startZone = "Western Plaguelands", startZoneMap = 1422, startedById = 11023, startedByDisplay = 10457 },
	{ id = 5531, name = "Betina Bigglezink", level = 60, minLevel = 57, startedBy = "Leonid Barthalomew the Revered", startZone = "Eastern Plaguelands", startZoneMap = 1423, startedById = 11036, startedByDisplay = 10474 },
	{ id = 4771, name = "Dawn's Gambit", level = 60, minLevel = 57, startedBy = "Betina Bigglezink", startZone = "Eastern Plaguelands", startZoneMap = 1423, startedById = 11035, startedByDisplay = 10465, rewards = { 15853, 15854 } },
	{ id = 5384, name = "Kirtonos the Herald", level = 60, minLevel = 55, startedBy = "Eva Sarkhoff", startZone = "Western Plaguelands", startZoneMap = 1422, startedById = 11216, startedByDisplay = 10895, rewards = { 13544, 15805, 15806 } },
	{ id = 5515, name = "Krastinov's Bag of Horrors", level = 60, minLevel = 55, startedBy = "Eva Sarkhoff", startZone = "Western Plaguelands", startZoneMap = 1422, startedById = 11216, startedByDisplay = 10895 },
	{ id = 8969, name = "The Left Piece of Lord Valthalak's Amulet", level = 60, minLevel = 58, startedBy = "Bodley", startedById = 16033, startedByDisplay = 15994 },
	{ id = 8992, name = "The Right Piece of Lord Valthalak's Amulet", level = 60, minLevel = 58, startedBy = "Bodley", startedById = 16033, startedByDisplay = 15994 },
})
