--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Stratholme.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Stratholme", {
	{ id = 5263, name = "Above and Beyond", level = 60, minLevel = 55, startedBy = "Duke Nicholas Zverenhoff", startZone = "Eastern Plaguelands" },
	{ id = 5125, name = "Aurius' Reckoning", level = 60, minLevel = 55, startedBy = "Aurius", startZone = "Stratholme", rewards = { 17044, 17045 } },
	{ id = 8945, name = "Dead Man's Plea", level = 60, minLevel = 58, startedBy = "Anthion Harmon", startZone = "Eastern Plaguelands", rewards = { 22137 } },
	{ id = 5243, name = "Houses of the Holy", level = 60, minLevel = 55, startedBy = "Leonid Barthalomew the Revered", startZone = "Eastern Plaguelands", rewards = { 3928, 6149, 13216, 13217 } },
	{ id = 5463, name = "Menethil's Gift", level = 60, minLevel = 57, startedBy = "Leonid Barthalomew the Revered", startZone = "Eastern Plaguelands" },
	{ id = 5848, name = "Of Love and Family", level = 60, minLevel = 52, startedBy = "Artist Renfray", startZone = "Western Plaguelands" },
	{ id = 6163, name = "Ramstein", level = 60, minLevel = 56, side = "Horde", startedBy = "Nathanos Blightcaller", startZone = "Eastern Plaguelands", rewards = { 17001, 18022 } },
	{ id = 5213, name = "The Active Agent", level = 60, minLevel = 55, startedBy = "Betina Bigglezink", startZone = "Eastern Plaguelands", rewards = { 13209, 19812 } },
	{ id = 5251, name = "The Archivist", level = 60, minLevel = 55, startedBy = "Duke Nicholas Zverenhoff", startZone = "Eastern Plaguelands" },
	{ id = 5212, name = "The Flesh Does Not Lie", level = 60, minLevel = 55, startedBy = "Betina Bigglezink", startZone = "Eastern Plaguelands" },
	{ id = 5214, name = "The Great Fras Siabi", level = 60, minLevel = 55, startedBy = "Smokey LaRue", startZone = "Eastern Plaguelands", rewards = { 13171 } },
	{ id = 8968, name = "The Left Piece of Lord Valthalak's Amulet", level = 60, minLevel = 58, startedBy = "Bodley" },
	{ id = 5122, name = "The Medallion of Faith", level = 60, minLevel = 55, startedBy = "Aurius", startZone = "Stratholme" },
	{ id = 5282, name = "The Restless Souls", level = 60, minLevel = 55, startedBy = "Egan", startZone = "Eastern Plaguelands", rewards = { 13315 } },
	{ id = 8991, name = "The Right Piece of Lord Valthalak's Amulet", level = 60, minLevel = 58, startedBy = "Bodley" },
	{ id = 5262, name = "The Truth Comes Crashing Down", level = 60, minLevel = 55 },
})
