--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Uldaman.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Uldaman", {
	{ id = 721, name = "A Sign of Hope", level = 35, minLevel = 35, side = "Alliance", startedBy = "Prospector Ryedol", startZone = "Badlands" },
	{ id = 2418, name = "Power Stones", level = 36, minLevel = 30, startedBy = "Rigglefuzz", startZone = "Badlands", rewards = { 9522, 10358, 10359 } },
	{ id = 704, name = "Agmond's Fate", level = 38, minLevel = 30, side = "Alliance", startedBy = "Prospector Ironband", startZone = "Loch Modan", rewards = { 4980 } },
	{ id = 722, name = "Amulet of Secrets", level = 40, minLevel = 35, side = "Alliance", startedBy = "Hammertoe Grez", startZone = "Loch Modan" },
	{ id = 709, name = "Solution to Doom", level = 40, minLevel = 30, startedBy = "Theldurin the Lost", startZone = "Badlands", rewards = { 4746 } },
	{ id = 2240, name = "The Hidden Chamber", level = 40, minLevel = 35, side = "Alliance", startedBy = "Baelog", startZone = "Uldaman", rewards = { 9626, 9627 } },
	{ id = 2398, name = "The Lost Dwarves", level = 40, minLevel = 35, side = "Alliance", startedBy = "Prospector Stormpike", startZone = "Ironforge" },
	{ id = 2199, name = "Lore for a Price", level = 41, minLevel = 37, side = "Alliance", startedBy = "Talvash del Kissel", startZone = "Ironforge" },
	{ id = 2283, name = "Necklace Recovery", level = 41, minLevel = 37, side = "Horde", startedBy = "Dran Droffers", startZone = "Orgrimmar" },
	{ id = 2198, name = "The Shattered Necklace", level = 41, minLevel = 37, side = "Alliance", startedBy = "Archmage Allistarj", startZone = "Blasted Lands" },
	{ id = 2200, name = "Back to Uldaman", level = 42, minLevel = 37, side = "Alliance", startedBy = "Talvash del Kissel", startZone = "Ironforge" },
	{ id = 3375, name = "Replacement Phial", level = 42, minLevel = 37, side = "Alliance", startedBy = "Talvash del Kissel", startZone = "Ironforge", rewards = { 7667 } },
	{ id = 2318, name = "Translating the Journal", level = 42, minLevel = 37, side = "Horde", startedBy = "Remains of a Paladin", startZone = "Uldaman" },
	{ id = 2338, name = "Translating the Journal", level = 42, minLevel = 37, side = "Horde", startedBy = "Jarkal Mossmeld", startZone = "Badlands" },
	{ id = 17, name = "Uldaman Reagent Run", level = 42, minLevel = 36, side = "Alliance", startedBy = "Ghak Healtouch", startZone = "Loch Modan", rewards = { 9030 } },
	{ id = 2202, name = "Uldaman Reagent Run", level = 42, minLevel = 36, side = "Horde", startedBy = "Jarkal Mossmeld", startZone = "Badlands", rewards = { 9030 } },
	{ id = 2201, name = "Find the Gems", level = 43, minLevel = 40, side = "Alliance", startedBy = "Remains of a Paladin", startZone = "Uldaman" },
	{ id = 1360, name = "Reclaimed Treasures", level = 43, minLevel = 33, side = "Alliance", startedBy = "Krom Stoutarm", startZone = "Ironforge" },
	{ id = 2342, name = "Reclaimed Treasures", level = 43, minLevel = 33, side = "Horde", startedBy = "Patrick Garrett", startZone = "Undercity" },
	{ id = 2340, name = "Deliver the Gems", level = 44, minLevel = 37, side = "Horde", startedBy = "Jarkal Mossmeld", startZone = "Badlands" },
	{ id = 2339, name = "Find the Gems and Power Source", level = 44, minLevel = 37, side = "Horde", startedBy = "Jarkal Mossmeld", startZone = "Badlands" },
	{ id = 2204, name = "Restoring the Necklace", level = 44, minLevel = 37, side = "Alliance" },
	{ id = 2361, name = "Restoring the Necklace", level = 44, minLevel = 37, side = "Alliance", startedBy = "Talvash del Kissel", startZone = "Ironforge", rewards = { 7673 } },
	{ id = 1139, name = "The Lost Tablets of Will", level = 45, minLevel = 35, side = "Alliance", startedBy = "Advisor Belgrum", startZone = "Ironforge", rewards = { 6723 } },
	{ id = 2278, name = "The Platinum Discs", level = 47, minLevel = 40 },
	{ id = 2279, name = "The Platinum Discs", level = 47, minLevel = 40, side = "Alliance" },
	{ id = 2280, name = "The Platinum Discs", level = 47, minLevel = 40, side = "Horde" },
})
