--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV

Dungeon quests for Zul'Farrak.

Generated by tools/gen_dungeon_quests.py from a local Questie checkout. Do not
edit by hand; re-run the tool instead.
]]
select(2, ...).SetupGlobalFacade()

QuestService.Register("Zul'Farrak", {
	{ id = 2865, name = "Scarab Shells", level = 45, minLevel = 40, startedBy = "Tran\\'rek", startZone = "Tanaris", startedById = 7876, startedByDisplay = 11379 },
	{ id = 2936, name = "The Spider God", level = 45, minLevel = 40, side = "Horde", startedBy = "Master Gadrin", startZone = "Durotar", startedById = 3188, startedByDisplay = 4072 },
	{ id = 2864, name = "Tran'rek", level = 45, minLevel = 40, startedBy = "Krazek", startZone = "Stranglethorn Vale", startedById = 773, startedByDisplay = 7164 },
	{ id = 3042, name = "Troll Temper", level = 45, minLevel = 40, startedBy = "Trenton Lighthammer", startZone = "Tanaris", startedById = 7804, startedByDisplay = 6868 },
	{ id = 2861, name = "Tabetha's Task", level = 46, minLevel = 40, startedBy = "Ursyn Ghull", startZone = "Thunder Bluff", startedById = 3048, startedByDisplay = 6058 },
	{ id = 2846, name = "Tiara of the Deep", level = 46, minLevel = 40, startedBy = "Tabetha", startZone = "Dustwallow Marsh", startedById = 6546, startedByDisplay = 5375, rewards = { 9527, 9531 } },
	{ id = 2768, name = "Divino-matic Rod", level = 47, minLevel = 40, startedBy = "Chief Engineer Bilgewhizzle", startZone = "Tanaris", startedById = 7407, startedByDisplay = 7169, rewards = { 9533, 9534 } },
	{ id = 2991, name = "Nekrum's Medallion", level = 47, minLevel = 40, side = "Alliance", startedBy = "Thadius Grimshade", startZone = "Blasted Lands", startedById = 8022, startedByDisplay = 7273 },
	{ id = 3527, name = "The Prophecy of Mosh'aru", level = 47, minLevel = 40, startedBy = "Yeh\\'kinya", startZone = "Tanaris", startedById = 8579, startedByDisplay = 7902 },
	{ id = 2770, name = "Gahz'rilla", level = 50, minLevel = 40, startedBy = "Wizzle Brassbolts", startZone = "Thousand Needles", startedById = 4453, startedByDisplay = 5428, rewards = { 11122 } },
})
