--[[
Copyright (C) 2023 FooxyTV (simon@fooxy.tv)
All rights reserved.

Programming by: FooxyTV
]]
select(2, ...).SetupGlobalFacade()

--[[
The quest graph: which quests belong to which chain, and where this character stands
on each link.

This is the point of the whole feature. Questie will tell you where a quest is; it
will not tell you that this is step three of seven, that the next link wants level 22,
or that you can no longer take it because you picked the other side of a branch.
Chains and hidden prerequisites are where people actually get lost.

Data comes from data/Quests/, generated by tools/questie_import.lua -- never
hand-written. QuestLogService supplies the character's actual state; this service adds
the reasoning on top and holds no quest state of its own.
]]

QuestChainService = { }

local zones = { }        -- uiMapID -> { expansion, quests = { } }
local questsByID = { }   -- id -> quest

-- Standard WoW race and class bitmasks, which is how Questie stores quest gating.
local RACE_BITS = {
	Human = 1, Orc = 2, Dwarf = 4, NightElf = 8, Scourge = 16,
	Tauren = 32, Gnome = 64, Troll = 128, BloodElf = 512, Draenei = 1024,
}
local CLASS_BITS = {
	WARRIOR = 1, PALADIN = 2, HUNTER = 4, ROGUE = 8, PRIEST = 16,
	SHAMAN = 64, MAGE = 128, WARLOCK = 256, DRUID = 1024,
}

local function IsBurningCrusade()
	return select(4, GetBuildInfo()) >= 20000
end

--[[
Registration. The importer emits one call per zone per expansion; only the set
matching this client is kept, since the TBC database is a superset of Classic's and
loading both would double every zone.
]]
function QuestChainService.AddQuests(expansion, uiMapID, quests)
	local wanted = IsBurningCrusade() and "tbc" or "era"
	if expansion ~= wanted then return end

	zones[uiMapID] = { expansion = expansion, quests = quests }
	for _, quest in ipairs(quests) do
		quest.uiMapID = uiMapID
		questsByID[quest.id] = quest
	end
end

function QuestChainService.GetQuest(questID)
	return questsByID[questID]
end

function QuestChainService.GetZones()
	local result = { }
	for uiMapID, zone in pairs(zones) do
		table.insert(result, { uiMapID = uiMapID, count = #zone.quests })
	end
	table.sort(result, function(a, b) return a.uiMapID < b.uiMapID end)
	return result
end

function QuestChainService.GetQuestsForZone(uiMapID)
	local zone = zones[uiMapID]
	return zone and zone.quests or { }
end

-- Status ------------------------------------------------------------------------

local function HasBit(mask, bit)
	if not mask or mask == 0 or not bit then return true end
	return math.floor(mask / bit) % 2 == 1
end

local function AnyCompleted(ids)
	if not ids then return true end
	for _, id in ipairs(ids) do
		local quest = questsByID[id]
		if QuestLogService.IsCompleted(quest and quest.name, id) then return true end
	end
	return false
end

local function AllCompleted(ids)
	if not ids then return true end
	for _, id in ipairs(ids) do
		local quest = questsByID[id]
		if not QuestLogService.IsCompleted(quest and quest.name, id) then return false end
	end
	return true
end

local function MissingPrerequisite(quest)
	if quest.pre and not AnyCompleted(quest.pre) then
		-- preQuestSingle means ANY of these; name the first as the one to do.
		local first = questsByID[quest.pre[1]]
		return first and first.name or ("quest " .. tostring(quest.pre[1]))
	end
	if quest.preAll and not AllCompleted(quest.preAll) then
		for _, id in ipairs(quest.preAll) do
			local other = questsByID[id]
			if not QuestLogService.IsCompleted(other and other.name, id) then
				return other and other.name or ("quest " .. tostring(id))
			end
		end
	end
	return nil
end

--[[
Where this character stands on a quest.

Returns a status and, when blocked, the reason -- which is the part worth having.
"Blocked" on its own is no more useful than Questie simply not showing the quest.

	completed  handed in
	active     in the log now
	available  could be picked up
	blocked    cannot yet, with `reason` and `detail` saying why
]]
function QuestChainService.GetStatus(quest, inLog)
	if not quest then return "blocked" end

	if QuestLogService.IsCompleted(quest.name, quest.id) then
		return "completed"
	end

	inLog = inLog or (select(1, QuestLogService.GetQuestLogState()))
	if inLog[quest.name] then
		return "active"
	end

	local race = PlayerContextService.GetRace()
	if quest.races and race and RACE_BITS[race] and not HasBit(quest.races, RACE_BITS[race]) then
		return "blocked", "race", "not available to your race"
	end

	local class = PlayerContextService.GetClass()
	if quest.classes and class and CLASS_BITS[class]
		and not HasBit(quest.classes, CLASS_BITS[class]) then
		return "blocked", "class", "not available to your class"
	end

	local level = PlayerContextService.GetLevel()
	if quest.req and quest.req > level then
		return "blocked", "level", ("requires level %d"):format(quest.req)
	end

	local missing = MissingPrerequisite(quest)
	if missing then
		return "blocked", "prerequisite", ("after %s"):format(missing)
	end

	return "available"
end

-- Chains --------------------------------------------------------------------------

local function PrerequisitesOf(quest)
	local ids = { }
	for _, list in ipairs({ quest.pre, quest.preAll }) do
		if list then
			for _, id in ipairs(list) do table.insert(ids, id) end
		end
	end
	return ids
end

--[[
Groups a zone's quests into chains.

Chains are the connected components of the prerequisite graph, restricted to quests in
the same zone -- a chain that wanders into another zone is shown in the zone it starts
in, which is where someone would look for it.

Each quest carries a depth: how many links deep it sits. That is what lets the UI show
"step 3 of 7" rather than an unordered pile.

Quests with no prerequisites and nothing depending on them are not chains at all, and
are returned separately. Mixing one-off quests in amongst real chains is most of what
makes a quest list hard to read.
]]
function QuestChainService.GetChains(uiMapID)
	local quests = QuestChainService.GetQuestsForZone(uiMapID)
	local inZone, dependents = { }, { }
	for _, quest in ipairs(quests) do inZone[quest.id] = quest end

	for _, quest in ipairs(quests) do
		for _, id in ipairs(PrerequisitesOf(quest)) do
			if inZone[id] then
				dependents[id] = dependents[id] or { }
				table.insert(dependents[id], quest.id)
			end
		end
	end

	-- Union-find over the prerequisite edges.
	local parent = { }
	local function Find(id)
		while parent[id] and parent[id] ~= id do id = parent[id] end
		return id
	end
	local function Union(a, b)
		local rootA, rootB = Find(a), Find(b)
		if rootA ~= rootB then parent[rootB] = rootA end
	end
	for _, quest in ipairs(quests) do parent[quest.id] = quest.id end
	for _, quest in ipairs(quests) do
		for _, id in ipairs(PrerequisitesOf(quest)) do
			if inZone[id] then Union(id, quest.id) end
		end
	end

	local groups = { }
	for _, quest in ipairs(quests) do
		local root = Find(quest.id)
		groups[root] = groups[root] or { }
		table.insert(groups[root], quest)
	end

	-- Depth: longest prerequisite path inside the zone. Memoised, and guarded against
	-- a cycle in the data rather than trusting it not to have one.
	local depths, visiting = { }, { }
	local function Depth(id)
		if depths[id] then return depths[id] end
		if visiting[id] then return 0 end
		visiting[id] = true
		local best = 0
		local quest = inZone[id]
		if quest then
			for _, preID in ipairs(PrerequisitesOf(quest)) do
				if inZone[preID] then
					local candidate = Depth(preID) + 1
					if candidate > best then best = candidate end
				end
			end
		end
		visiting[id] = nil
		depths[id] = best
		return best
	end

	local chains, standalone = { }, { }
	for _, group in pairs(groups) do
		for _, quest in ipairs(group) do
			quest.depth = Depth(quest.id)
		end
		table.sort(group, function(a, b)
			if a.depth ~= b.depth then return a.depth < b.depth end
			if (a.level or 0) ~= (b.level or 0) then return (a.level or 0) < (b.level or 0) end
			return (a.name or "") < (b.name or "")
		end)
		if #group > 1 then
			--[[
			Is this a straight line or a tree?

			Elwynn's opening is a good example of why it matters: "A Threat Within"
			unlocks three separate branches, so calling it "step 3 of 12" would be
			nonsense. Linear chains genuinely do have steps and are worth numbering;
			branching ones are shown by their nesting instead.
			]]
			local atDepth = { }
			for _, quest in ipairs(group) do
				atDepth[quest.depth] = (atDepth[quest.depth] or 0) + 1
			end
			local linear = true
			for _, count in pairs(atDepth) do
				if count > 1 then linear = false break end
			end
			group.linear = linear
			group.root = group[1]
			table.insert(chains, group)
		else
			table.insert(standalone, group[1])
		end
	end

	table.sort(chains, function(a, b)
		local aLevel = a[1] and a[1].level or 0
		local bLevel = b[1] and b[1].level or 0
		if aLevel ~= bLevel then return aLevel < bLevel end
		return (a[1].name or "") < (b[1].name or "")
	end)
	table.sort(standalone, function(a, b)
		if (a.level or 0) ~= (b.level or 0) then return (a.level or 0) < (b.level or 0) end
		return (a.name or "") < (b.name or "")
	end)

	return chains, standalone
end

-- Debug helpers (see todo.md) -------------------------------------------------

_G.AGC_QuestChains = function(uiMapID)
	uiMapID = uiMapID or PlayerContextService.GetZone()
	local chains, standalone = QuestChainService.GetChains(uiMapID)
	print(("|cff33ff99[AGC]|r zone %s: %d chain(s), %d standalone")
		:format(tostring(uiMapID), #chains, #standalone))
	local inLog = QuestLogService.GetQuestLogState()
	for index, chain in ipairs(chains) do
		print(("  chain %d (%d quests, %s):"):format(index, #chain,
			chain.linear and "linear" or "branching"))
		for _, quest in ipairs(chain) do
			local status, _, detail = QuestChainService.GetStatus(quest, inLog)
			print(("    %s[%d] %-40s lvl %-3s %s%s"):format(
				string.rep("  ", quest.depth or 0), quest.id, quest.name,
				tostring(quest.level or "?"), status, detail and (" (" .. detail .. ")") or ""))
		end
	end
end
