"""
Extracts an NPC id -> creature display id map from the CMaNGOS Classic 1.12.1
world database, and writes it as a TSV for tools/questie_import.lua to read.

    python tools/extract_npc_models.py [path/to/ClassicDB_*.sql.gz]

Build-time only, and run rarely: the output is checked in as tools/npc_models.tsv
so a normal quest-data regeneration needs neither the 13MB dump nor the network.

Why this source. Questie knows which NPC starts a quest and which NPC you have to
kill for it, but it carries no display ids, and the Classic client ships Creature.db2
empty -- so nothing on the machine can turn an NPC id into a model. CMaNGOS's
creature_template is 1.12.1 data, which is exactly the era the addon supports, and its
ModelId columns are CreatureDisplayInfo ids: the same thing PlayerModel:SetDisplayInfo
takes and the same space as data/CreatureModels.lua already uses for bosses.

    https://github.com/cmangos/classic-db  (GPL-2.0)

Only Entry, Name and ModelId1 are taken. The alternative models (ModelId2-4) are the
random variants a spawn can pick; showing the first is what a player recognises.
"""

import gzip
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DUMP = os.path.join(HERE, "ClassicDB_1_12_1_z2815.sql.gz")
OUT = os.path.join(HERE, "npc_models.tsv")

ENTRY, NAME, MODEL_ID_1 = 0, 1, 5
INSERT = "INSERT INTO `creature_template` VALUES "


def split_tuples(payload):
    """
    Yields each (...) group from a SQL VALUES payload as a list of raw fields.

    Written by hand rather than with a regex because the rows contain quoted names
    with commas and escaped quotes in them ("Kurzen's Agent", 'Dun Garok Rifleman'),
    and a regex that splits on commas quietly corrupts exactly those rows.
    """
    field, fields, in_quote, escaped, depth = [], [], False, False, 0
    for char in payload:
        if escaped:
            field.append(char)
            escaped = False
        elif char == "\\":
            field.append(char)
            escaped = True
        elif in_quote:
            if char == "'":
                in_quote = False
            else:
                field.append(char)
        elif char == "'":
            in_quote = True
        elif char == "(":
            depth += 1
            if depth == 1:
                field, fields = [], []
        elif char == ")":
            depth -= 1
            if depth == 0:
                fields.append("".join(field))
                yield fields
                field, fields = [], []
        elif char == "," and depth == 1:
            fields.append("".join(field))
            field = []
        else:
            field.append(char)


def main():
    dump = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DUMP
    if not os.path.exists(dump):
        sys.exit(
            "cannot find %s\n"
            "Download it first:\n"
            "  curl -sSLo %s \\\n"
            "    https://raw.githubusercontent.com/cmangos/classic-db/master/"
            "Full_DB/ClassicDB_1_12_1_z2815.sql.gz" % (dump, dump)
        )

    rows, skipped = {}, 0
    opener = gzip.open if dump.endswith(".gz") else open
    with opener(dump, "rt", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            if not line.startswith(INSERT):
                continue
            for fields in split_tuples(line[len(INSERT):]):
                if len(fields) <= MODEL_ID_1:
                    skipped += 1
                    continue
                try:
                    entry = int(fields[ENTRY])
                    display = int(fields[MODEL_ID_1])
                except ValueError:
                    skipped += 1
                    continue
                name = fields[NAME].replace("\\'", "'").replace('\\"', '"')
                # A display of 0 means the server picks one of the alternates; with no
                # spawn to ask, there is nothing to show, so leave it out entirely
                # rather than write a row that renders an empty frame.
                if display > 0 and name:
                    rows[entry] = (name, display)

    with open(OUT, "w", encoding="utf-8", newline="\n") as out:
        out.write("# npc id\tdisplay id\tname\n")
        out.write("# Generated by tools/extract_npc_models.py from the CMaNGOS\n")
        out.write("# Classic 1.12.1 world database (GPL-2.0).\n")
        for entry in sorted(rows):
            name, display = rows[entry]
            out.write("%d\t%d\t%s\n" % (entry, display, name))

    print("wrote %s" % OUT)
    print("  %d npcs with a display id%s"
          % (len(rows), (", %d rows skipped" % skipped) if skipped else ""))
    for probe in (6, 197, 823):
        if probe in rows:
            print("  [%d] %s -> display %d" % (probe, rows[probe][0], rows[probe][1]))


if __name__ == "__main__":
    main()
