name: "Build and Publish Artifact - AdventureGuideClassic"

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      release_type:
        description: "CurseForge Release Type (alpha, beta, release)"
        required: false
        default: "alpha"
      game_versions:
        description: "Game Version(s)"
        required: false
        default: "1.15.5"
jobs:
  publish-addon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up scripts
        run: |
          chmod +x ./ci/scripts/lint.sh
          chmod +x ./ci/scripts/package.sh
          chmod +x ./ci/scripts/repackage.sh

      # - name: Lint
      #   run: |
      #     ./ci/scripts/lint.sh

      - name: Package
        run: |
          ./ci/scripts/package.sh

      - name: Repackage
        run: |
          ./ci/scripts/repackage.sh

      - name: Select correct artifact
        id: find_artifact
        run: |
          echo "Searching for artifact..."
          ZIP_FILE=$(ls ci/dist/[0-9]*.zip | head -n 1)

          if [ -z "$ZIP_FILE" ]; then
            echo "No matching artifact found."
            exit 1
          fi 

          echo "Found artifact: $ZIP_FILE"
          echo "ZIP_PATH=$ZIP_FILE" >> $GITHUB_ENV

      - name: Publish to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: ${{ env.ZIP_PATH }}
          project_id: ${{ secrets.CURSEFORGE_PROJECT_ID }}
          game_endpoint: "wow"
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          release_type: ${{ github.event.inputs.release_type }}
          changelog: "- Publish test to CurseForge from GitHub Actions." # Data within this changelog.txt file should be automatically generated
          changelog_type: "markdown"
          game_versions: ${{ github.event.inputs.game_versions }} # This needs to be a parameter so it's configurable or automatically generated

